### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0000Artur0000** [BananaPuncher714/RadioBoard#1]
[01:31:43] [Server thread/ERROR]: Error occurred while enabling RadioBoard v1.3 (Is it up to date?)
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_191]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_191]
	at java.awt.Image.getScaledInstance(Image.java:178) ~[?:1.8.0_191]
	at io.github.bananapuncher714.radioboard.providers.canvas.RadioCanvas.<init>(RadioCanvas.java:59) ~[?:?]
	at io.github.bananapuncher714.radioboard.providers.canvas.RadioCanvasFactory.deserialize(RadioCanvasFactory.java:37) ~[?:?]
	at io.github.bananapuncher714.radioboard.RadioBoard.loadBoardsFrom(RadioBoard.java:139) ~[?:?]
	at io.github.bananapuncher714.radioboard.RadioBoard.loadConfig(RadioBoard.java:113) ~[?:?]
	at io.github.bananapuncher714.radioboard.RadioBoard.onEnable(RadioBoard.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-529]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by BananaPuncher714** [comment]
What java version are you running?
